### ISSUE TITLE
Move FightEvent to event.action package

### ISSUE THREAD

**Issue by palra** [palra/univ-mmorpg#13]
You should refactor class `fr.univdevs.mmorpg.engine.event.FightEvent.FightEvent` to `fr.univdevs.mmorpg.engine.event.action.FightEvent`. Not only `FightEvent`is an invalid package name (it should be in lowercase), but it doesn't respect the event package naming convention set at #5.

**Comment by palra** [comment]
I re-read your code, and it seems you misunderstood how we should organise pour event classes in the event package.

An event is designed by its topic and its name. Events can be, then, represented in a tree, where events are agregated by their topic name. So, our events must be named that way : `fr.univdevs.mmorpg.engine.event.<topic>.<name>Event`

Don't forget that, for example, a CureEvent extends of ActionEvent, so it inherits of its topic. No need to create a constructor to initialize the topic of the event in ActionEvent, and so on CureEvent that doesn't need to have a constructor parameter for its event name, as it will be common to every instance of CureEvent (`action.cure`)

**Comment by drattak** [comment]
I know. Mistake
For event classes, I just c/p classes already existing
