### ISSUE TITLE
Switch to ArrayList in World#entities

### ISSUE THREAD

**Issue by palra** [palra/univ-mmorpg#14]
Methods to change : 
- [x]  `addEntity`
- [x]  `removeEntity`
- [x]  `getEntity`
- [x]  `getEntities`
- [x] `isCollidableAt`

**Comment by drattak** [comment]
How do you want to switch to arrayList, from a Vector2D?

**Comment by palra** [comment]
We don't have to use it there, because the key of an HashMap should never changes, but the position of an Entity in the world can change.
