### ISSUE TITLE
Change Inventory#has(Item) to Inventory#has(Object)

### ISSUE THREAD

**Issue by palra** [palra/univ-mmorpg#20]
https://github.com/palra/univ-mmorpg/blob/feature/serialization/src/main/java/fr/univdevs/mmorpg/engine/character/Inventory.java#L174-L182

In Java, `HashMap<K,V>#containsValue` takes an Object in parameter, even it its generic form, so we should follow the rules.
See : http://docs.oracle.com/javase/7/docs/api/java/util/Map.html#containsValue(java.lang.Object)

We should also change the `remove` method so it takes an `Object` in parameter too, as `HashMap<K,V>#remove(Object)`
- [ ] `has(Item)` -> `has(Object)`
- [ ] `remove(Item)` -> `remove(Object)`

**Comment by drattak** [comment]
Why? It doesn't seem so important

**Comment by palra** [comment]
Just for compatibility with the Java standards, otherwise that's not so important
