### ISSUE TITLE
Utility of Inventory#getItemByCategory()

### ISSUE THREAD

**Issue by palra** [palra/univ-mmorpg#21]
https://github.com/palra/univ-mmorpg/blob/feature/serialization/src/main/java/fr/univdevs/mmorpg/engine/character/Inventory.java#L233-L236

Isn't that a (bad) duplicate of `Inventory#getByType(String)` ?

**Comment by drattak** [comment]
The name is wrong, but one returns only one item, the first of its category, and the other one returns all categories

**Comment by palra** [comment]
So `Item#getFirstOfCategory(String)` ? It looks useless

**Comment by drattak** [comment]
Indeed, equivalent to getByType[x]

**Comment by palra** [comment]
So, do we keep it ?

**Comment by palra** [comment]
So, it's "no"
