### ISSUE TITLE
Remove MAX_RESISTANCE and MAX_HEALTH

### ISSUE THREAD

**Issue by palra** [palra/univ-mmorpg#22]
https://github.com/palra/univ-mmorpg/blob/feature/serialization/src/main/java/fr/univdevs/mmorpg/engine/character/Character.java#L13-L14

I think that `MAX_RESISTANCE` and `MAX_HEALTH` constants are bad, because it implies that the engines decides what the gameplay should be like. This is a bad thing : an engine should not make assumptions on the gameplay that the final user want to implement.
(this is not a major issue, so it can be delayed after the due date)

**Comment by drattak** [comment]
So, where ?

**Comment by palra** [comment]
Where what ?

**Comment by drattak** [comment]
Not in the engine, but where ? I think we need these constants

**Comment by palra** [comment]
In a mother class of all the Character of our games, somewhere in `game.character`

**Comment by drattak** [comment]
or maybe in the Healer and Warrior classes ?

**Comment by palra** [comment]
Nope, this behavior should be global to all the character of the game
