### ISSUE TITLE
How to specify the cure

### ISSUE THREAD

**Issue by drattak** [palra/univ-mmorpg#25]
How do we specify the cure we want to use ? 
Now, we type the ID, but that's not user-friendly

**Comment by palra** [comment]
For the moment, this is the only way to select the right item, if we use the category name, first nothing says that such an element exists in the curernt character's inventory, and we can't specify a signe item by using the category name, as we can have multiple items of a same category
In itself, typing `move left 25` isn't very user-friendly, but we have to make it work in a console, so I think this is the only way to make it work correctly.

**Comment by drattak** [comment]
Ok
