### ISSUE TITLE
Exceptions

### ISSUE THREAD

**Issue by drattak** [palra/univ-mmorpg#26]
https://github.com/palra/univ-mmorpg/blob/develop/src/main/java/fr/univdevs/mmorpg/bridge/FightCommand.java#L22-L38

This throws CommandException, what if I need to throw an InvalidArgumentException ?

**Comment by drattak** [comment]
`else return "Vous avez entré une arme invalide";`
 ?

**Comment by palra** [comment]
Instead, throw an [ArgumentValidationCommandException](https://github.com/palra/univ-mmorpg/blob/develop/src/main/java/fr/univdevs/commander/ArgumentValidationCommandException.java)

**Comment by palra** [comment]
FYI, there is some exceptions already defined for some known cases : https://github.com/palra/univ-mmorpg/tree/develop/src/main/java/fr/univdevs/commander
