### ISSUE TITLE
CureAction constructor should throw exception when the given character can't cure

### ISSUE THREAD

**Issue by palra** [palra/univ-mmorpg#27]
https://github.com/palra/univ-mmorpg/blob/feature/serialization/src/main/java/fr/univdevs/mmorpg/engine/action/CureAction.java

CureAction should accept only `Character`s that implements `CanCure`. The same with `FightAction` and `CanFight`. It should check it at the constructor, and associated exception should be created in the `skills` package
- [ ] `CureAction()`, `CanCure`
- [ ] `FightAction()`, `CanFight`

**Comment by drattak** [comment]
Skill package deleted
