### ISSUE TITLE
Inventory should not inherit from LoggerAwareInterface

### ISSUE THREAD

**Issue by palra** [palra/univ-mmorpg#32]
It is not the role of Inventory to add an event, but the responsability of actions, for instance the MoveAction for InventoryAddEvent

**Comment by palra** [comment]
UML updated :white_check_mark:

**Comment by drattak** [comment]
And for remove ?

**Comment by drattak** [comment]
I mean, MoveAction adds an Item, but do not remove one, and we need to add this to log when needed

**Comment by palra** [comment]
You will log the event when you will use the `Inventory#remove` method,

**Comment by drattak** [comment]
Well, I created drop command and dropAction

**Comment by palra** [comment]
I will had to modify ItemsCommand so, it had an uncomplete drop method, I will delete it

**Comment by drattak** [comment]
Oke,
