### ISSUE TITLE
Kill character when hp <= 0

### ISSUE THREAD

**Issue by drattak** [palra/univ-mmorpg#33]
We need to kill, and stop the game when a character is dead

**Comment by palra** [comment]
Stop the entire game ?

**Comment by drattak** [comment]
no, stop the game if there's only one character alive

**Comment by palra** [comment]
Ok, right, take a look at the `Game#play` method. I suggest the creation of `GameManager#isGameFinished` (put in on Game or GameManager ? As it depends of the gameplay of the user, I would say Game)

**Comment by palra** [comment]
I also suggest the `Character#isDead() : boolean`  method
